// Creat web server
// npm install express
// npm install body-parser
// npm install mongoose
// npm install ejs
// npm install express-sanitizer
// npm install method-override
// npm install moment
// npm install passport
// npm install passport-local
// npm install passport-local-mongoose
// npm install express-session
// npm install connect-flash
// npm install multer
// npm install cloudinary
// npm install dotenv
// npm install nodemailer
// npm install nodemailer-smtp-transport
// npm install async
// npm install crypto
// npm install request
// npm install cheerio